version: 1
feeds:
  - "https://xeonds.github.io/atom"
  - "https://www.superbart.top/index.xml"
  - "https://raay.xyz/feed"
  - "https://blog.woooo.tech/index.xml"
  - "https://blog.ksfu.top/atom.xml"
  - "http://blog.xiaobeo.top/index.php/feed/"
  - "https://canxin121.github.io/index.xml"
  - "https://blog.frankli.site/atom.xml"
  - "https://hawa130.com/feed"
  - "https://www.mukiispace.tk/rss/feed.xml"
  - "https://www.shifeiti.com/atom.xml"
  - "https://honoka.tech/atom.xml"
  - "https://www.aweip.com/index.php/feed/"
  - "https://www.forestlee.top/atom.xml"
  - "https://www.indevn.com/index.xml"
  - "https://xiue233.github.io/atom.xml"
  - "https://blog.lsy223622.com/feed/atom"
  - "https://wanglanhuajiaofen.fun/atom.xml"
  - "https://hhzm.win/rss.xml"
  - "https://hiangzahoong.github.io/atom.xml"
  - "https://nancunchild.cn/feed/"
  - "https://note.stalomeow.com/rss.xml"
  - "https://guzhengsvt.top/index.php/feed/atom/"
  - "https://blog.zyar.top/json/“
